### ISSUE TITLE
Update links into openbmc/docs

### ISSUE THREAD

**Issue by joseph-reynolds** [mine260309/openbmc-intro#2]
The intro has some links into the https://github.com/openbmc/docs repo which have moved into subdirectories.  For example, openbmc-systemd.md moved into architecture/openbmc-systemd.md.  The links should be updated.

https://github.com/openbmc/docs/blob/master/architecture/openbmc-systemd.md

**Comment by mine260309** [comment]
Thanks for reporting this.
I am glad that this repo has an interest in the community. Will update the links.
